<a href="https://colab.research.google.com/github/Geetanjali-Kumari1/FutureIQ/blob/main/FutureIQ1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Geetanjali-Kumari1/FutureIQ/main/purchase_history_10000.csv')

In [ ]:
df.head()

Customer ID  Gender  Age  Salary Product ID  Price  Purchased
0            1  Female   49   61000        P01   2000          1
1            2    Male   36   30000        P02   2000          1
2            3  Female   26   81000        P02   3500          1
3            4  Female   32   74000        P01   7000          0
4            5  Female   42   56000        P01   5000          0

In [ ]:
df.count()

Customer ID    10000
Gender         10000
Age            10000
Salary         10000
Product ID     10000
Price          10000
Purchased      10000
dtype: int64

In [ ]:
len(df)

10000

In [ ]:
one_hot_encoded_df = pd.get_dummies(df, columns=['Gender'])

In [ ]:
one_hot_encoded_df['Gender_Female'] = one_hot_encoded_df['Gender_Female'].astype(int)
one_hot_encoded_df['Gender_Male'] = one_hot_encoded_df['Gender_Male'].astype(int)

In [ ]:
print(one_hot_encoded_df.head())

   Customer ID  Age  Salary Product ID  Price  Purchased  Gender_Female  \
0            1   49   61000        P01   2000          1              1   
1            2   36   30000        P02   2000          1              0   
2            3   26   81000        P02   3500          1              1   
3            4   32   74000        P01   7000          0              1   
4            5   42   56000        P01   5000          0              1   

   Gender_Male  
0            0  
1            1  
2            0  
3            0  
4            0  


In [ ]:
one_hot_encoded_df = one_hot_encoded_df.drop(columns=['Gender_Female'])

In [ ]:
print(one_hot_encoded_df.head())

   Customer ID  Age  Salary Product ID  Price  Purchased  Gender_Male
0            1   49   61000        P01   2000          1            0
1            2   36   30000        P02   2000          1            1
2            3   26   81000        P02   3500          1            0
3            4   32   74000        P01   7000          0            0
4            5   42   56000        P01   5000          0            0


In [ ]:
df_with_gender = pd.concat([df['Gender'], one_hot_encoded_df], axis=1)

In [ ]:
print(one_hot_encoded_df.head())

   Customer ID  Age  Salary Product ID  Price  Purchased  Gender_Male
0            1   49   61000        P01   2000          1            0
1            2   36   30000        P02   2000          1            1
2            3   26   81000        P02   3500          1            0
3            4   32   74000        P01   7000          0            0
4            5   42   56000        P01   5000          0            0


In [ ]:
print(df_with_gender.head())

   Gender  Customer ID  Age  Salary Product ID  Price  Purchased  Gender_Male
0  Female            1   49   61000        P01   2000          1            0
1    Male            2   36   30000        P02   2000          1            1
2  Female            3   26   81000        P02   3500          1            0
3  Female            4   32   74000        P01   7000          0            0
4  Female            5   42   56000        P01   5000          0            0


In [ ]:
x = df_with_gender[['Gender_Male','Age','Salary','Price']].to_numpy()

In [ ]:
x

array([[    0,    49, 61000,  2000],
       [    1,    36, 30000,  2000],
       [    0,    26, 81000,  3500],
       ...,
       [    0,    41, 20000,  2000],
       [    1,    22, 29000,  5000],
       [    0,    49, 36000,  3500]])

In [ ]:
y = df_with_gender['Purchased'].to_numpy()


In [ ]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
x_train, x_temp, y_train, y_temp = train_test_split(x, y, test_size=0.4, random_state=42)


In [ ]:
x_val, x_test, y_val, y_test = train_test_split(x_temp, y_temp, test_size=0.5, random_state=42)


In [ ]:
print(f'Training set size: {len(x_train)}')


Training set size: 6000


In [ ]:
print(f'Cross-validation set size: {len(x_val)}')


Cross-validation set size: 2000


In [ ]:
print(f'Test set size: {len(x_test)}')


Test set size: 2000


In [ ]:
x_train


array([[    1,    30, 48000,  3500],
       [    0,    59, 60000,  5000],
       [    1,    28, 94000,  7000],
       ...,
       [    1,    62, 97000,  7000],
       [    0,    59, 91000,  2000],
       [    0,    47, 73000,  5000]])

In [ ]:
x_test


array([[    0,    45, 67000,  7000],
       [    1,    56, 80000,  5000],
       [    1,    40, 20000,  5000],
       ...,
       [    1,    43, 64000,  7000],
       [    1,    25, 39000,  7000],
       [    1,    63, 83000,  2000]])

In [ ]:
y_train


array([0, 1, 0, ..., 0, 1, 0])

In [ ]:
y_test


array([0, 1, 0, ..., 0, 0, 1])

In [ ]:
x_temp

array([[    0,    48, 39000,  5000],
       [    0,    38, 37000,  3500],
       [    0,    51, 88000,  2000],
       ...,
       [    1,    60, 60000,  7000],
       [    0,    52, 47000,  5000],
       [    1,    25, 49000,  7000]])

In [ ]:
y_temp

array([0, 1, 1, ..., 0, 0, 0])

In [ ]:
x_val

array([[    0,    37, 24000,  2000],
       [    0,    49, 81000,  2000],
       [    0,    43, 50000,  5000],
       ...,
       [    0,    18, 40000,  2000],
       [    1,    62, 98000,  3500],
       [    0,    27, 79000,  7000]])

In [ ]:
y_val

array([0, 1, 0, ..., 0, 1, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler


In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_val = scaler.transform(x_val)
x_test = scaler.fit_transform(x_test)



In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [ ]:
log_reg_model = LogisticRegression()


In [ ]:
log_reg_model.fit(x_train, y_train)



LogisticRegression()

In [ ]:
y_val_pred_log_reg = log_reg_model.predict(x_val)


In [ ]:
print("Logistic Regression Cross-Validation Classification Report:")
print(classification_report(y_val, y_val_pred_log_reg))

Logistic Regression Cross-Validation Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.84      0.82      1196
           1       0.74      0.69      0.72       804

    accuracy                           0.78      2000
   macro avg       0.77      0.76      0.77      2000
weighted avg       0.78      0.78      0.78      2000



In [ ]:
from sklearn.metrics import accuracy_score


In [ ]:
val_accuracy_log_reg = accuracy_score(y_val, y_val_pred_log_reg)
print("Logistic Regression Cross-Validation Accuracy:", val_accuracy_log_reg)


Logistic Regression Cross-Validation Accuracy: 0.7785


In [ ]:
y_test_pred_log_reg = log_reg_model.predict(x_test)

In [ ]:
print("Logistic Regression Test Set Classification Report:")
print(classification_report(y_test, y_test_pred_log_reg))

Logistic Regression Test Set Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.84      0.82      1141
           1       0.77      0.73      0.75       859

    accuracy                           0.79      2000
   macro avg       0.79      0.78      0.79      2000
weighted avg       0.79      0.79      0.79      2000



In [ ]:
test_accuracy_log_reg = accuracy_score(y_test, y_test_pred_log_reg)
print("Logistic Regression Test Set Accuracy:", test_accuracy_log_reg)

Logistic Regression Test Set Accuracy: 0.7915


In [ ]:
from sklearn.ensemble import RandomForestClassifier


In [ ]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
y_val_pred_rf = rf_model.predict(x_val)


In [ ]:
print("Random Forest Cross-Validation Classification Report:")
print(classification_report(y_val, y_val_pred_rf))



Random Forest Cross-Validation Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      1196
           1       0.99      1.00      0.99       804

    accuracy                           0.99      2000
   macro avg       0.99      1.00      0.99      2000
weighted avg       0.99      0.99      0.99      2000



In [ ]:
val_accuracy_rf = accuracy_score(y_val, y_val_pred_rf)
print("Random Forest Cross-Validation Accuracy:", val_accuracy_rf)

Random Forest Cross-Validation Accuracy: 0.9945


In [ ]:
y_test_pred_rf = rf_model.predict(x_test)

In [ ]:
print("Random Forest Test Set Classification Report:")
print(classification_report(y_test, y_test_pred_rf))

Random Forest Test Set Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1141
           1       0.99      0.98      0.98       859

    accuracy                           0.99      2000
   macro avg       0.99      0.99      0.99      2000
weighted avg       0.99      0.99      0.99      2000



In [ ]:
test_accuracy_rf = accuracy_score(y_test, y_test_pred_rf)
print("Random Forest Test Set Accuracy:", test_accuracy_rf)

Random Forest Test Set Accuracy: 0.987


In [ ]:
from sklearn.svm import SVC
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
svm_model = SVC(random_state=42)
svm_model.fit(x_train, y_train)


SVC(random_state=42)

In [ ]:
y_val_pred_svm = svm_model.predict(x_val)

In [ ]:
print("SVM Cross-Validation Classification Report:")
print(classification_report(y_val, y_val_pred_svm))

SVM Cross-Validation Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.84      0.83      1196
           1       0.75      0.74      0.75       804

    accuracy                           0.80      2000
   macro avg       0.79      0.79      0.79      2000
weighted avg       0.80      0.80      0.80      2000



In [ ]:
val_accuracy_svm = accuracy_score(y_val, y_val_pred_svm)
print("SVM Cross-Validation Accuracy:", val_accuracy_svm)

SVM Cross-Validation Accuracy: 0.7995


In [ ]:
y_test_pred_svm = svm_model.predict(x_test)

In [ ]:
print("SVM Test Set Classification Report:")
print(classification_report(y_test, y_test_pred_svm))

SVM Test Set Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.86      0.84      1141
           1       0.80      0.73      0.77       859

    accuracy                           0.81      2000
   macro avg       0.81      0.80      0.80      2000
weighted avg       0.81      0.81      0.81      2000



In [ ]:
test_accuracy_svm = accuracy_score(y_test, y_test_pred_svm)
print("SVM Test Set Accuracy:", test_accuracy_svm)

SVM Test Set Accuracy: 0.8085


In [ ]:
ann_model = Sequential()
ann_model.add(Dense(16, input_dim=x_train.shape[1], activation='relu'))
ann_model.add(Dense(8, activation='relu'))
ann_model.add(Dense(1, activation='sigmoid'))

In [ ]:
ann_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [ ]:
ann_model.fit(x_train, y_train, epochs=50, batch_size=10, validation_data=(x_val, y_val), verbose=1)


Epoch 1/50
600/600 [==============================] - 3s 2ms/step - loss: 0.5545 - accuracy: 0.7267 - val_loss: 0.4625 - val_accuracy: 0.7740
Epoch 2/50
600/600 [==============================] - 1s 2ms/step - loss: 0.4280 - accuracy: 0.7872 - val_loss: 0.4215 - val_accuracy: 0.7785
Epoch 3/50
600/600 [==============================] - 1s 2ms/step - loss: 0.4010 - accuracy: 0.7845 - val_loss: 0.3996 - val_accuracy: 0.7810
Epoch 4/50
600/600 [==============================] - 1s 2ms/step - loss: 0.3863 - accuracy: 0.7825 - val_loss: 0.3889 - val_accuracy: 0.7780
Epoch 5/50
600/600 [==============================] - 1s 2ms/step - loss: 0.3790 - accuracy: 0.7837 - val_loss: 0.3835 - val_accuracy: 0.7750
Epoch 6/50
600/600 [==============================] - 1s 2ms/step - loss: 0.3737 - accuracy: 0.7830 - val_loss: 0.3796 - val_accuracy: 0.7800
Epoch 7/50
600/600 [==============================] - 1s 2ms/step - loss: 0.3695 - accuracy: 0.7857 - val_loss: 0.3732 - val_accuracy: 0.7800
Epoch 

In [ ]:
val_loss, val_accuracy_ann = ann_model.evaluate(x_val, y_val, verbose=0)
print("ANN Cross-Validation Accuracy:", val_accuracy_ann)

ANN Cross-Validation Accuracy: 0.8069999814033508


In [ ]:
y_test_pred_ann = (ann_model.predict(x_test) > 0.5).astype("int32")


63/63 [==============================] - 0s 1ms/step


In [ ]:
print("ANN Test Set Classification Report:")
print(classification_report(y_test, y_test_pred_ann))

ANN Test Set Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.84      0.84      1141
           1       0.79      0.77      0.78       859

    accuracy                           0.81      2000
   macro avg       0.81      0.81      0.81      2000
weighted avg       0.81      0.81      0.81      2000



In [ ]:
test_accuracy_ann = accuracy_score(y_test, y_test_pred_ann)
print("ANN Test Set Accuracy:", test_accuracy_ann)

ANN Test Set Accuracy: 0.812


In [ ]:
import pickle

In [ ]:
with open('log_reg_model.pkl','wb') as f:
  pickle.dump(log_reg_model,f)

In [ ]:
with open('rf_model.pkl', 'wb') as f:
    pickle.dump(rf_model, f)

In [ ]:
with open('svm_model.pkl', 'wb') as f:
    pickle.dump(svm_model, f)

In [ ]:
with open('ann_model.pkl', 'wb') as f:
    pickle.dump(ann_model, f)

In [ ]:
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [ ]:
!ls

ann_model.h5   log_reg_model.pkl  sample_data  svm_model.pkl
ann_model.pkl  rf_model.pkl	  scaler.pkl
