<a href="https://colab.research.google.com/github/Geetanjali-Kumari1/FutureIQ/blob/main/test_futureiq.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pickle
with open('log_reg_model.pkl', 'rb') as f:
  log_reg_new = pickle.load(f)

In [ ]:
import pickle
with open('scaler.pkl', 'rb') as f:
  scaler_new = pickle.load(f)

In [ ]:
import pandas as pd



In [ ]:
new_df = pd.read_csv("https://raw.githubusercontent.com/Geetanjali-Kumari1/FutureIQ/main/new_customers.csv")

In [ ]:
new_df

Gender  Age  Salary  Product ID  Price
0    Male   24   38652           3   4446
1  Female   47   64727           1   5188
2    Male   46   54648           1   6193
3    Male   31   20018           3   4779
4    Male   58   77731           2   6855
5    Male   28   55478           1   6153
6  Female   48   54211           2   7588
7    Male   31   60076           3   5238
8  Female   42   29290           1   5418
9    Male   50   21445           1   5598

In [ ]:
len(new_df)

10

In [ ]:
one_hot_encoded_df_new = pd.get_dummies(new_df, columns=['Gender'])

In [ ]:
one_hot_encoded_df_new['Gender_Female'] = one_hot_encoded_df_new['Gender_Female'].astype(int)
one_hot_encoded_df_new['Gender_Male'] = one_hot_encoded_df_new['Gender_Male'].astype(int)

In [ ]:
one_hot_encoded_df_new

Age  Salary  Product ID  Price  Gender_Female  Gender_Male
0   24   38652           3   4446              0            1
1   47   64727           1   5188              1            0
2   46   54648           1   6193              0            1
3   31   20018           3   4779              0            1
4   58   77731           2   6855              0            1
5   28   55478           1   6153              0            1
6   48   54211           2   7588              1            0
7   31   60076           3   5238              0            1
8   42   29290           1   5418              1            0
9   50   21445           1   5598              0            1

In [ ]:
one_hot_encoded_df_new = one_hot_encoded_df_new.drop(columns=['Gender_Female'])

In [ ]:
one_hot_encoded_df_new

Age  Salary  Product ID  Price  Gender_Male
0   24   38652           3   4446            1
1   47   64727           1   5188            0
2   46   54648           1   6193            1
3   31   20018           3   4779            1
4   58   77731           2   6855            1
5   28   55478           1   6153            1
6   48   54211           2   7588            0
7   31   60076           3   5238            1
8   42   29290           1   5418            0
9   50   21445           1   5598            1

In [ ]:
print(one_hot_encoded_df_new.head())

   Age  Salary  Product ID  Price  Gender_Male
0   24   38652           3   4446            1
1   47   64727           1   5188            0
2   46   54648           1   6193            1
3   31   20018           3   4779            1
4   58   77731           2   6855            1


In [ ]:
df_with_gender_new = pd.concat([new_df['Gender'], one_hot_encoded_df_new], axis=1)

In [ ]:
print(df_with_gender_new.head())

   Gender  Age  Salary  Product ID  Price  Gender_Male
0    Male   24   38652           3   4446            1
1  Female   47   64727           1   5188            0
2    Male   46   54648           1   6193            1
3    Male   31   20018           3   4779            1
4    Male   58   77731           2   6855            1


In [ ]:
x_new = df_with_gender_new[['Gender_Male','Age','Salary','Price']].to_numpy()

In [ ]:
x_new

array([[    1,    24, 38652,  4446],
       [    0,    47, 64727,  5188],
       [    1,    46, 54648,  6193],
       [    1,    31, 20018,  4779],
       [    1,    58, 77731,  6855],
       [    1,    28, 55478,  6153],
       [    0,    48, 54211,  7588],
       [    1,    31, 60076,  5238],
       [    0,    42, 29290,  5418],
       [    1,    50, 21445,  5598]])

In [ ]:
x_new_scale2 = scaler_new.fit_transform(x_new)

In [ ]:
x_new_scale2

array([[ 0.65465367, -1.54774434, -0.48875298, -1.42543997],
       [-1.52752523,  0.60971747,  0.93112246, -0.61159228],
       [ 0.65465367,  0.51591478,  0.38228547,  0.49072164],
       [ 0.65465367, -0.89112553, -1.50343981, -1.06019565],
       [ 0.65465367,  1.64154703,  1.63923599,  1.21682294],
       [ 0.65465367, -1.17253359,  0.42748189,  0.44684845],
       [-1.52752523,  0.70352015,  0.35848928,  2.02079916],
       [ 0.65465367, -0.89112553,  0.67785916, -0.55675079],
       [-1.52752523,  0.14070403, -0.99854681, -0.35932143],
       [ 0.65465367,  0.89112553, -1.42573465, -0.16189207]])

In [ ]:
y_new_pred = log_reg_new.predict(x_new_scale2)

In [ ]:
y_new_pred

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0])

In [ ]:
df_with_gender_new['will_purchase'] = y_new_pred

In [ ]:
df_with_gender_new

Gender  Age  Salary  Product ID  Price  Gender_Male  will_purchase
0    Male   24   38652           3   4446            1              1
1  Female   47   64727           1   5188            0              1
2    Male   46   54648           1   6193            1              0
3    Male   31   20018           3   4779            1              0
4    Male   58   77731           2   6855            1              0
5    Male   28   55478           1   6153            1              0
6  Female   48   54211           2   7588            0              0
7    Male   31   60076           3   5238            1              1
8  Female   42   29290           1   5418            0              0
9    Male   50   21445           1   5598            1              0

In [ ]:
df_with_gender_new.to_csv("log_reg_model_predictions.csv",index=False)

In [ ]:
with open('svm_model.pkl', 'rb') as f:
  svm_new = pickle.load(f)

In [ ]:
y_new_pred = svm_new.predict(x_new_scale2)

In [ ]:
y_new_pred

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0])

In [ ]:
df_with_gender_new['will_purchase'] = y_new_pred

In [ ]:
df_with_gender_new

Gender  Age  Salary  Product ID  Price  Gender_Male  will_purchase
0    Male   24   38652           3   4446            1              0
1  Female   47   64727           1   5188            0              1
2    Male   46   54648           1   6193            1              0
3    Male   31   20018           3   4779            1              0
4    Male   58   77731           2   6855            1              0
5    Male   28   55478           1   6153            1              0
6  Female   48   54211           2   7588            0              0
7    Male   31   60076           3   5238            1              1
8  Female   42   29290           1   5418            0              0
9    Male   50   21445           1   5598            1              0

In [ ]:
df_with_gender_new.to_csv("svm_model_predictions.csv",index=False)

In [ ]:
with open('ann_model.pkl', 'rb') as f:
  ann_new = pickle.load(f)

In [ ]:
y_new_pred = ann_new.predict(x_new_scale2)

1/1 [==============================] - 0s 81ms/step


In [ ]:
y_new_pred

array([[5.5829638e-01],
       [8.3258098e-01],
       [1.7234320e-02],
       [5.1825489e-03],
       [1.1471076e-03],
       [3.7607670e-02],
       [1.2340699e-19],
       [4.3048376e-01],
       [7.2823018e-01],
       [1.1210025e-02]], dtype=float32)

In [ ]:
df_with_gender_new['will_purchase'] = y_new_pred

In [ ]:
df_with_gender_new

Gender  Age  Salary  Product ID  Price  Gender_Male  will_purchase
0    Male   24   38652           3   4446            1   5.582964e-01
1  Female   47   64727           1   5188            0   8.325810e-01
2    Male   46   54648           1   6193            1   1.723432e-02
3    Male   31   20018           3   4779            1   5.182549e-03
4    Male   58   77731           2   6855            1   1.147108e-03
5    Male   28   55478           1   6153            1   3.760767e-02
6  Female   48   54211           2   7588            0   1.234070e-19
7    Male   31   60076           3   5238            1   4.304838e-01
8  Female   42   29290           1   5418            0   7.282302e-01
9    Male   50   21445           1   5598            1   1.121003e-02

In [ ]:
df_with_gender_new.to_csv("ann_model_predictions.csv",index=False)

In [ ]:
with open('rf_model.pkl', 'rb') as f:
  rf_new = pickle.load(f)

In [ ]:
y_new_pred = rf_new.predict(x_new_scale2)

In [ ]:
y_new_pred

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 0])

In [ ]:
df_with_gender_new['will_purchase'] = y_new_pred

In [ ]:
df_with_gender_new

Gender  Age  Salary  Product ID  Price  Gender_Male  will_purchase
0    Male   24   38652           3   4446            1              1
1  Female   47   64727           1   5188            0              1
2    Male   46   54648           1   6193            1              1
3    Male   31   20018           3   4779            1              0
4    Male   58   77731           2   6855            1              0
5    Male   28   55478           1   6153            1              0
6  Female   48   54211           2   7588            0              0
7    Male   31   60076           3   5238            1              0
8  Female   42   29290           1   5418            0              1
9    Male   50   21445           1   5598            1              0

In [ ]:
df_with_gender_new.to_csv("rf_model_predictions.csv",index=False)